sudo: require

language: cpp

dist: bionic

addons:
  apt:
    sources:
    packages:
      - gcc-7
      - g++-7
      - cmake

install:
    - sudo apt-get install libboost-all-dev
    - sudo apt install libeigen3-dev
    - sudo apt-get install python3 python-dev python3-pip
    - pip install -r requirements.txt

script:
    - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
    - gcc -v && g++ -v && cmake --version
    - export CC=/usr/bin/gcc-7
    - export CXX=/usr/bin/g++-7
    - mkdir build && cd build && cmake ../ && make && make test