sudo: require

language: cpp

dist: bionic

env:
  - BLAS=OpenBLAS CTEST_OUTPUT_ON_FAILURE=1

cache:
  - ccache
  - pip


addons:
  apt:
    sources:
    packages:
      - gcc-7
      - g++-7
      - cmake

before_install:
  - test -n $CC && unset CC

install:
    - sudo apt install openmpi-bin libopenmpi-dev
    - sudo apt install libboost-all-dev libboost-mpi-dev libboost-mpi-python-dev
    - sudo apt install libopenblas-dev
    - sudo apt install libeigen3-dev
    - sudo apt install python3 python-dev python3-pip
    - sudo pip3 install -r requirements.txt
    - wget https://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2 && tar xjf 3.3.7.tar.bz2 && rm 3.3.7.tar.bz2 && cd eigen-eigen-323c052e1731 && mkdir build && cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local
    - sudo make -j2 install
    - cd ../..
    - rm -rf eigen-eigen-323c052e1731
    - wget https://github.com/LLNL/sundials/releases/download/v4.1.0/sundials-4.1.0.tar.gz && tar -xzf sundials-4.1.0.tar.gz && cd sundials-4.1.0/ && mkdir build && cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local
    - sudo make -j2 install
    - cd ../..
    - rm -rf sundials-4.1.0
    - wget https://github.com/stan-dev/math/archive/v2.17.1.tar.gz  && tar -xzf v2.17.1.tar.gz
    # with stan-math unpacked, we rely on the CMakeLists.txt to include it as an include directory

script:
    - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
    - gcc -v && g++ -v && cmake --version
    - export CC=/usr/bin/gcc-7
    - export CXX=/usr/bin/g++-7
    - mkdir build && cd build && cmake ../ 
    - make -j2
    - make test

