sudo: require

language: cpp

dist: bionic

env:
  - BLAS=OpenBLAS CTEST_OUTPUT_ON_FAILURE=1

cache:
  - ccache
  - pip

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'

    packages:
      - gcc-9
      - g++-9
      - gfortran
      - cmake

before_install:
  - test -n $CC && unset CC

install:
    - sudo apt-get update -qq
    - sudo apt install gcc-9 g++-9
    - sudo apt install openmpi-bin libopenmpi-dev
    - sudo apt install libboost-all-dev libboost-mpi-dev libboost-mpi-python-dev
    - sudo apt install libopenblas-dev liblapack-dev
    - sudo apt install libgsl-dev
    - sudo apt install python3 python-dev python3-pip
    - sudo apt install python3-setuptools
    - sudo pip3 install -r requirements.txt
    - sudo apt-get install autoconf
    - wget http://www.met.reading.ac.uk/clouds/adept/adept-2.0.5.tar.gz
    - tar -xvf adept-2.0.5.tar.gz
    - cd adept-2.0.5/
    - ./configure && make -j2 && sudo make install
    - cd include && ./create_adept_source_header
    - ls
    - pwd
    - ls /usr/local/include/
    - sudo cp adept_source.h /usr/local/include/
    - cd ../..

script:
    - sudo ln -s /usr/bin/gcc-9 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-9 /usr/local/bin/g++
    - gcc -v && g++ -v && cmake --version
    - export CC=/usr/bin/gcc-9
    - export CXX=/usr/bin/g++-9
    - mkdir build && cd build && cmake ../ 
    - make -j2
    - make test

