name: build publish Test Pypi

on:
  push:
    tags:
      - '*'

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest] # ubuntu-20.04, windows-latest, macos-latest, (macos-11.0)?
        python_minor_version: [8 ] # 6, 7, 8, 9

    steps:
      # For windows, install latest nuget package manager
      - name: Setup windows nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest
        if: matrix.os == 'windows-latest'

      - name: Install windows nuget packages
        run: |
          Register-PackageSource -provider NuGet -name nugetRepository -location https://www.nuget.org/api/v2
          Install-Package -Force gsl-msvc-x64
          Install-Package -Force Python3${{matrix.python_minor_version}}
          Install-Package -Force boost-vc142
          Install-Package -Force boost_atomic-vc142
          Install-Package -Force boost_chrono-vc142
          Install-Package -Force boost_date_time-vc142
          Install-Package -Force boost_fiber-vc142
          Install-Package -Force boost_filesystem-vc142
          Install-Package -Force boost_graph-vc142
          Install-Package -Force boost_iostreams-vc142
          Install-Package -Force boost_locale-vc142
          Install-Package -Force boost_log-vc142
          Install-Package -Force boost_log_setup-vc142
          Install-Package -Force boost_regex-vc142
          Install-Package -Force boost_serialization-vc142
          Install-Package -Force boost_system-vc142
          Install-Package -Force boost_thread-vc142
          Install-Package -Force boost_timer-vc142
          Install-Package -Force boost_unit_test_framework-vc142
          Install-Package -Force boost_program_options-vc142
          Install-Package -Force boost_python3${{matrix.python_minor_version}}-vc142
          Install-Package -Force boost_wserialization-vc142
          Install-Package -Force boost_zlib-vc142
          nuget locals all -list
        # dir C:\Users\runneradmin\.nuget\packages\
        shell: powershell
        if: matrix.os == 'windows-latest'

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.${{matrix.python_minor_version}}'

      # Install msbuild
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        if: matrix.os == 'windows-latest'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==1.6.3 twine
        shell: bash

      - name: Update and install gsl
        run: |
          yum update
          yum install -y wget epel-release gsl gsl-devel
        shell: bash
        if: matrix.os == 'ubuntu-20.04'

      - name: Install brew packages MacOS
        run: |
          brew update >/dev/null
          brew install gcc gsl
        shell: bash
        if: matrix.os == 'macos-latest'

      - name: Install Adept MacOS and Linux
        run: |
          wget http://www.met.reading.ac.uk/clouds/adept/adept-2.0.5.tar.gz
          tar -xf adept-2.0.5.tar.gz
          cd adept-2.0.5/
          ./configure --disable-fortran
          make -j2
          make install
          cd include
          ./create_adept_source_header
          cp adept_source.h /usr/local/include/
          cd ~
        shell: bash
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-20.04'

      # on MacOS, we find python at for example: /Users/runner/hostedtoolcache/Python/3.8.6/x64
      - name: Macos diagnostics
        run: |
          ls /Users/runner/hostedtoolcache/Python/
          echo '---------'
          ls /Users/runner/hostedtoolcache/Python/3.8.6/
          echo '---------'
          ls /Users/runner/hostedtoolcache/Python/3.8.6/x64/
          echo '---------'
          ls /Users/runner/hostedtoolcache/Python/3.8.6/x64/include/
          echo '---------'
          ls /Users/runner/hostedtoolcache/Python/3.8.6/x64/lib/
        if: matrix.os == 'macos-latest'

      - name: Install boost Macos
        run: |
          wget https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.gz > /dev/null 2>&1
          tar -xzf boost_1_*
          cd boost_1_*
          ./bootstrap.sh
          echo "using gcc ;" > project-config.jam && echo "project : default-build <toolset>gcc ;" >> project-config.jam && echo "import python ;" >> project-config.jam
          echo "using python    : 3.${{matrix.python_minor_version}}    :  /Users/runner/hostedtoolcache/Python/3.8.6/x64/bin/python    : /Users/runner/hostedtoolcache/Python/3.8.6/x64/include/    : /Users/runner/hostedtoolcache/Python/3.8.6/x64/lib/ ;" >> project-config.jam
          ./b2 cxxflags=-std=c++17 install -j 8 --with=all
        if: matrix.os == 'macos-latest'
        # || matrix.os == 'windows latest'

      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}

          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BUILD: 'cp3${{matrix.python_minor_version}}-manylinux* cp3${{matrix.python_minor_version}}-macosx_x86_64 cp3${{matrix.python_minor_version}}-win_amd64'
          CIBW_BEFORE_BUILD_WINDOWS: 'choco install wget && wget http://www.met.reading.ac.uk/clouds/adept/adept-2.0.5.tar.gz > $null && tar -xf adept-2.0.5.tar.gz'
          #CIBW_BEFORE_BUILD_MACOS: ''
          CIBW_BEFORE_ALL_LINUX: 'wget https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.gz > /dev/null 2>&1 && tar -xzf boost_1_* && cd boost_1_* && ./bootstrap.sh && echo "using gcc ;" > project-config.jam && echo "project : default-build <toolset>gcc ;" >> project-config.jam && echo "import python ;" >> project-config.jam &&   echo "using python    : 3.${{matrix.python_minor_version}}    :  /opt/python/cp3${{matrix.python_minor_version}}-cp3${{matrix.python_minor_version}}/bin/python    : /opt/python/cp3${{matrix.python_minor_version}}-cp3${{matrix.python_minor_version}}/include/python3.${{matrix.python_minor_version}}/    : /opt/python/cp3${{matrix.python_minor_version}}-cp3${{matrix.python_minor_version}}/lib/python3.${{matrix.python_minor_version}}/ ;" >> project-config.jam && ./b2 install -j 8 --with=all > /dev/null 2>&1 && cd ~ && wget http://www.met.reading.ac.uk/clouds/adept/adept-2.0.5.tar.gz && tar -xf adept-2.0.5.tar.gz && cd adept-2.0.5/ && ./configure && make -j2 && make install && cd include && ./create_adept_source_header && cp adept_source.h /usr/local/include/'

        run: |
          python -m cibuildwheel --output-dir distribution
          python -m twine upload --repository testpypi distribution/*

        continue-on-error: true
