name: Integrate TestPypi package.

#
on:
  push:
    tags:
      - '*'

jobs:
  build_wheels:
    name: "Package ${{ matrix.os }} | CP 3.${{matrix.python_minor_version}}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        python_minor_version: [7, 8, 9]
    steps:

      ########################################################################################################################


      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: "[All] Install Python 3.${{matrix.python_minor_version}}"
        with:
          python-version: '3.${{matrix.python_minor_version}}'

      - name: "[All] Test Python installation"
        run: |
          python -c "import os, sys; from sysconfig import get_paths; print(os.path.dirname(sys.executable)); print(get_paths())"

      ########################################################################################################################

      - name: "[All] Install Library from test pypi and run tests"
        run: |
          python -m pip install --index-url https://test.pypi.org/simple/ eslpy --force
          python -m pip show eslpy

      - name: "[MacOS] Delocate test"
        run: |
          python -m pip install delocate
          wget https://test-files.pythonhosted.org/packages/8a/21/86c93b8ff2f08266d4cdfea0d4915fd0a210cfba34945555420e71cbe13e/eslpy-0.0.80-cp37-cp37m-macosx_10_9_x86_64.whl
          delocate-listdeps --depending eslpy-0.0.80-cp37-cp37m-macosx_10_9_x86_64.whl
        if: matrix.os == 'macos-10.15' && matrix.python_minor_version == 7


      - name: "[MacOS] Delocate test"
        run: |
          python -m pip install delocate
          wget https://test-files.pythonhosted.org/packages/da/19/1fb82d00511ffb5b462a26a5c7db46770b850eb718ee12d5bdda91b5ff13/eslpy-0.0.80-cp38-cp38-macosx_10_9_x86_64.whl
          delocate-listdeps --depending eslpy-0.0.80-cp38-cp38-macosx_10_9_x86_64.whl
        if: matrix.os == 'macos-10.15' && matrix.python_minor_version == 8


      ########################################################################################################################

      - name: "[All] Install Library from test pypi and run tests"
        run: |
          mkdir pythontest
          cd pythontest
          python -c "import esl; print(esl.version())"
        continue-on-error: true

